.github/workflows/gradle.yml

:rocket: gradle.yml 수정

---

README.md

:memo: Docs: README.md 수정

---

src/main/java/com/likelion/helfoome/global/auth/handler/CustomSuccessHandler.java
src/main/java/com/likelion/helfoome/global/config/swagger/SwaggerConfig.java

🔧 Settings: Redirect URI 수정

---

src/main/java/com/likelion/helfoome/HelFooMeApplication.java
src/main/java/com/likelion/helfoome/domain/shop/controller/ShopController.java
src/main/java/com/likelion/helfoome/domain/shop/dto/ShopRegisterRequest.java
src/main/java/com/likelion/helfoome/domain/shop/dto/TaxIdRequest.java
src/main/java/com/likelion/helfoome/domain/shop/entity/ShopEntity.java
src/main/java/com/likelion/helfoome/domain/shop/repository/ShopRepository.java
src/main/java/com/likelion/helfoome/domain/shop/service/ShopService.java
src/main/java/com/likelion/helfoome/domain/user/controller/UserController.java
src/main/java/com/likelion/helfoome/domain/user/service/UserService.java

✨ Feat: Shop Entity 생성

---

src/main/java/com/likelion/helfoome/domain/Img/entity/ProductImg.java
src/main/java/com/likelion/helfoome/domain/shop/controller/ProductController.java
src/main/java/com/likelion/helfoome/domain/shop/dto/ProductRequest.java
src/main/java/com/likelion/helfoome/domain/shop/entity/Product.java
src/main/java/com/likelion/helfoome/domain/shop/service/ProductService.java

:sparkles: Feat: create seller post

---

src/main/java/com/likelion/helfoome/domain/Img/entity/ArticleImg.java
src/main/java/com/likelion/helfoome/domain/Img/entity/CommunityImg.java
src/main/java/com/likelion/helfoome/domain/Img/service/ImgService.java

이미지 업로드 근데 product만 일단 우선 구현함
article, community는 아직 엔티티가 안채워져서 안 건드림

:sparkles: Feat: Image Upload

---

src/main/java/com/likelion/helfoome/domain/shop/service/ProductService.java

:sparkles: Feat: create sales post

---

build.gradle
src/main/java/com/likelion/helfoome/domain/cart/entity/Cart.java
src/main/java/com/likelion/helfoome/domain/cart/entity/CartProduct.java
src/main/java/com/likelion/helfoome/domain/post/entity/Article.java
src/main/java/com/likelion/helfoome/domain/post/entity/ArticleLike.java
src/main/java/com/likelion/helfoome/domain/post/entity/Comment.java
src/main/java/com/likelion/helfoome/domain/post/entity/Community.java
src/main/java/com/likelion/helfoome/domain/post/entity/CommunityLike.java
src/main/java/com/likelion/helfoome/domain/shop/entity/Shop.java
src/main/java/com/likelion/helfoome/domain/user/entity/Notification.java
src/main/java/com/likelion/helfoome/domain/user/entity/Order.java
src/main/java/com/likelion/helfoome/domain/user/entity/OrderProduct.java
src/main/java/com/likelion/helfoome/domain/user/repository/NotificationRepository.java
src/main/java/com/likelion/helfoome/global/config/s3/S3Config.java

✨ Feat: Entity Field 생성

---

src/main/java/com/likelion/helfoome/domain/shop/controller/ProductController.java

♻️ Refactor: Endpoint 변경

---

src/main/java/com/likelion/helfoome/domain/shop/dto/ShopRegisterRequest.java
src/main/java/com/likelion/helfoome/domain/shop/entity/Shop.java
src/main/java/com/likelion/helfoome/domain/shop/service/ShopService.java
src/main/java/com/likelion/helfoome/global/config/SecurityConfig.java

:recycle: Refactor: Api 경로 권한 부여

---

src/main/java/com/likelion/helfoome/global/auth/handler/CustomSuccessHandler.java
src/main/java/com/likelion/helfoome/global/config/SecurityConfig.java
src/main/java/com/likelion/helfoome/global/config/swagger/SwaggerConfig.java

CORS error 처리를 위한 config 파일 수정

🔧 Settings: CORS error 처리

---

src/main/java/com/likelion/helfoome/domain/post/controller/CommentController.java
src/main/java/com/likelion/helfoome/domain/post/controller/LikeController.java
src/main/java/com/likelion/helfoome/domain/post/dto/CommentRequest.java
src/main/java/com/likelion/helfoome/domain/post/repository/ArticleLikeRepository.java
src/main/java/com/likelion/helfoome/domain/post/repository/CommunityLikeRepository.java
src/main/java/com/likelion/helfoome/domain/post/repository/DemandLikeRepository.java
src/main/java/com/likelion/helfoome/domain/post/repository/SupplyLikeRepository.java
src/main/java/com/likelion/helfoome/domain/post/service/CommentService.java
src/main/java/com/likelion/helfoome/domain/post/service/LikeService.java
src/main/java/com/likelion/helfoome/domain/post/service/PostService.java

:bug: Fix: Fix conflict

---

.github/workflows/gradle.yml
src/main/java/com/likelion/helfoome/domain/post/controller/CommentController.java

🗃️ Comment: Swagger description 변경

---

src/main/java/com/likelion/helfoome/domain/shop/controller/ShopController.java
src/main/java/com/likelion/helfoome/domain/shop/dto/ShopRegisterRequest.java
src/main/java/com/likelion/helfoome/domain/shop/service/ShopService.java

사진 파일 받아와서 S3에 업로드하고 URL, name저장하는 로직으로 수정했습니다
Service, Controller(RequsetBody->ModelAttribute), ShopRegisterRequest 세 파일 수정함요

:sparkles: Feat: ShopImage Upload

---

src/main/java/com/likelion/helfoome/domain/cart/controller/CartController.java
src/main/java/com/likelion/helfoome/domain/cart/dto/AddProductRequest.java
src/main/java/com/likelion/helfoome/domain/cart/dto/CartProductResponse.java
src/main/java/com/likelion/helfoome/domain/cart/entity/Cart.java
src/main/java/com/likelion/helfoome/domain/cart/entity/CartProduct.java
src/main/java/com/likelion/helfoome/domain/cart/repository/CartProductRepository.java
src/main/java/com/likelion/helfoome/domain/cart/repository/CartRepository.java
src/main/java/com/likelion/helfoome/domain/cart/service/CartService.java
src/main/java/com/likelion/helfoome/domain/shop/dto/ShopRegisterRequest.java
src/main/java/com/likelion/helfoome/domain/shop/service/ShopService.java
src/main/java/com/likelion/helfoome/domain/user/dto/UserInfoRegisterRequest.java
src/main/java/com/likelion/helfoome/domain/user/service/UserInfoService.java

:sparkles: Feat: Cart 관련 기능 추가

---

src/main/java/com/likelion/helfoome/HelFooMeApplication.java
src/main/java/com/likelion/helfoome/domain/order/service/OrderService.java
src/main/java/com/likelion/helfoome/domain/shop/controller/ProductController.java
src/main/java/com/likelion/helfoome/domain/user/controller/StampController.java
src/main/java/com/likelion/helfoome/domain/user/controller/UserInfoController.java
src/main/java/com/likelion/helfoome/domain/user/dto/StampResponse.java
src/main/java/com/likelion/helfoome/domain/user/entity/Stamp.java
src/main/java/com/likelion/helfoome/domain/user/repository/StampRepository.java
src/main/java/com/likelion/helfoome/domain/user/service/StampService.java
src/main/java/com/likelion/helfoome/global/Scheduler/Scheduler.java

:sparkles: Feature:  Stamp

---

src/main/java/com/likelion/helfoome/domain/order/entity/Order.java
src/main/java/com/likelion/helfoome/domain/post/repository/ArticleRepository.java
src/main/java/com/likelion/helfoome/domain/post/repository/CommunityRepository.java
src/main/java/com/likelion/helfoome/domain/post/repository/DemandRepository.java
src/main/java/com/likelion/helfoome/domain/post/repository/SupplyRepository.java
src/main/java/com/likelion/helfoome/domain/shop/controller/ProductController.java
src/main/java/com/likelion/helfoome/domain/shop/dto/product/MainProductResponse.java
src/main/java/com/likelion/helfoome/domain/shop/entity/Shop.java
src/main/java/com/likelion/helfoome/domain/shop/repository/ProductRepository.java
src/main/java/com/likelion/helfoome/domain/shop/service/ProductService.java
src/main/java/com/likelion/helfoome/domain/user/controller/SearchController.java
src/main/java/com/likelion/helfoome/domain/user/dto/SearchResponse.java
src/main/java/com/likelion/helfoome/domain/user/entity/Search.java
src/main/java/com/likelion/helfoome/domain/user/repository/SearchRepository.java
src/main/java/com/likelion/helfoome/domain/user/service/SearchService.java

[검색 기능 개발](https://github.com/2024-4lineton/BackEnd/commit/0925a88248298cbefdbd302d00837c2cb47979ae)

:sparkles: Feat: 검색 기능 개발

---

src/main/java/com/likelion/helfoome/domain/order/controller/OrderController.java
src/main/java/com/likelion/helfoome/domain/shop/service/ProductService.java
src/main/java/com/likelion/helfoome/domain/user/controller/UserController.java
src/main/java/com/likelion/helfoome/domain/user/service/UserService.java

:sparkles: Feat: 닉네임 중복 확인 기능 추가

---

src/main/java/com/likelion/helfoome/domain/shop/controller/ProductController.java
src/main/java/com/likelion/helfoome/domain/shop/controller/ShopController.java
src/main/java/com/likelion/helfoome/domain/shop/service/ProductService.java

🗃️ Comment: Shop description 변경

---

.github/workflows/gradle.yml
src/main/java/com/likelion/helfoome/domain/shop/controller/ProductController.java
src/main/java/com/likelion/helfoome/domain/shop/controller/ShopController.java
src/main/java/com/likelion/helfoome/domain/shop/service/ProductService.java

♻️ Refactor: 라스트 찬스 로직 변경

---

src/main/java/com/likelion/helfoome/domain/shop/service/ProductService.java
src/main/java/com/likelion/helfoome/domain/user/controller/UserController.java
src/main/java/com/likelion/helfoome/domain/user/controller/UserInfoController.java
src/main/java/com/likelion/helfoome/domain/user/service/UserService.java
src/main/java/com/likelion/helfoome/global/auth/handler/CustomSuccessHandler.java
src/main/java/com/likelion/helfoome/global/config/SecurityConfig.java

🐛 Fix: 닉네임 중복 확인 오류 수정
